[package]
name = "ssh-idp"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.86"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.40", features = ["rt-multi-thread", "macros"] }

humantime = "2"
shellish_parse = "2"

# Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tree = "0.4"

# SSH handling
russh = "0.54"
async-trait = "0.1.82"
ssh-key = "0.6"

# JWT handling
jsonwebtoken = { version = "10.0.0", features = ["aws_lc_rs"] }
serde = { version = "1", features = ["derive"] }
rsa = "0.9.6"
base64ct = "1.6"

# HTTP handling
axum = { version = "0.8", features = ["macros"] }
tower-http = { version = "0.6", features = ["trace"] }

[profile.release]
debug = "line-tables-only"
